// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: req_robot.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace webwx {

  /// <summary>Holder for reflection information generated from req_robot.proto</summary>
  public static partial class ReqRobotReflection {

    #region Descriptor
    /// <summary>File descriptor for req_robot.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ReqRobotReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9yZXFfcm9ib3QucHJvdG8SBXdlYnd4GhJjb21tb25fcm9ib3QucHJvdG8i",
            "fgoIUm9ib3RSZXESCwoDY21kGAEgASgFEiMKC2NoYXRNc2dMaXN0GAIgAygL",
            "Mg4ud2Vid3guQ2hhdE1zZxIhCghpZGVudGl0eRgDIAEoCzIPLndlYnd4Lklk",
            "ZW50aXR5Eh0KBnJlc3VsdBgEIAEoCzINLndlYnd4LlJlc3VsdEIIqgIFd2Vi",
            "d3hiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::webwx.CommonRobotReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::webwx.RobotReq), global::webwx.RobotReq.Parser, new[]{ "Cmd", "ChatMsgList", "Identity", "Result" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RobotReq : pb::IMessage<RobotReq> {
    private static readonly pb::MessageParser<RobotReq> _parser = new pb::MessageParser<RobotReq>(() => new RobotReq());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RobotReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::webwx.ReqRobotReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RobotReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RobotReq(RobotReq other) : this() {
      cmd_ = other.cmd_;
      chatMsgList_ = other.chatMsgList_.Clone();
      Identity = other.identity_ != null ? other.Identity.Clone() : null;
      Result = other.result_ != null ? other.Result.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RobotReq Clone() {
      return new RobotReq(this);
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 1;
    private int cmd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Cmd {
      get { return cmd_; }
      set {
        cmd_ = value;
      }
    }

    /// <summary>Field number for the "chatMsgList" field.</summary>
    public const int ChatMsgListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::webwx.ChatMsg> _repeated_chatMsgList_codec
        = pb::FieldCodec.ForMessage(18, global::webwx.ChatMsg.Parser);
    private readonly pbc::RepeatedField<global::webwx.ChatMsg> chatMsgList_ = new pbc::RepeatedField<global::webwx.ChatMsg>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::webwx.ChatMsg> ChatMsgList {
      get { return chatMsgList_; }
    }

    /// <summary>Field number for the "identity" field.</summary>
    public const int IdentityFieldNumber = 3;
    private global::webwx.Identity identity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::webwx.Identity Identity {
      get { return identity_; }
      set {
        identity_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 4;
    private global::webwx.Result result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::webwx.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RobotReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RobotReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cmd != other.Cmd) return false;
      if(!chatMsgList_.Equals(other.chatMsgList_)) return false;
      if (!object.Equals(Identity, other.Identity)) return false;
      if (!object.Equals(Result, other.Result)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cmd != 0) hash ^= Cmd.GetHashCode();
      hash ^= chatMsgList_.GetHashCode();
      if (identity_ != null) hash ^= Identity.GetHashCode();
      if (result_ != null) hash ^= Result.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cmd != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Cmd);
      }
      chatMsgList_.WriteTo(output, _repeated_chatMsgList_codec);
      if (identity_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Identity);
      }
      if (result_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Result);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cmd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cmd);
      }
      size += chatMsgList_.CalculateSize(_repeated_chatMsgList_codec);
      if (identity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Identity);
      }
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RobotReq other) {
      if (other == null) {
        return;
      }
      if (other.Cmd != 0) {
        Cmd = other.Cmd;
      }
      chatMsgList_.Add(other.chatMsgList_);
      if (other.identity_ != null) {
        if (identity_ == null) {
          identity_ = new global::webwx.Identity();
        }
        Identity.MergeFrom(other.Identity);
      }
      if (other.result_ != null) {
        if (result_ == null) {
          result_ = new global::webwx.Result();
        }
        Result.MergeFrom(other.Result);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Cmd = input.ReadInt32();
            break;
          }
          case 18: {
            chatMsgList_.AddEntriesFrom(input, _repeated_chatMsgList_codec);
            break;
          }
          case 26: {
            if (identity_ == null) {
              identity_ = new global::webwx.Identity();
            }
            input.ReadMessage(identity_);
            break;
          }
          case 34: {
            if (result_ == null) {
              result_ = new global::webwx.Result();
            }
            input.ReadMessage(result_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
