// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resp_robot.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace webwx {

  /// <summary>Holder for reflection information generated from resp_robot.proto</summary>
  public static partial class RespRobotReflection {

    #region Descriptor
    /// <summary>File descriptor for resp_robot.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RespRobotReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChByZXNwX3JvYm90LnByb3RvEgV3ZWJ3eBoSY29tbW9uX3JvYm90LnByb3Rv",
            "ImUKEFNlcnZpY2VSb2JvdFJlc3ASCwoDY21kGAEgASgFEh8KB2NoYXRNc2cY",
            "AiABKAsyDi53ZWJ3eC5DaGF0TXNnEiMKCW9wZXJhdGlvbhgDIAEoCzIQLndl",
            "Ynd4Lk9wZXJhdGlvbkIIqgIFd2Vid3hiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::webwx.CommonRobotReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::webwx.ServiceRobotResp), global::webwx.ServiceRobotResp.Parser, new[]{ "Cmd", "ChatMsg", "Operation" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  ///IM 工作机后台 cmd 
  /// </summary>
  public sealed partial class ServiceRobotResp : pb::IMessage<ServiceRobotResp> {
    private static readonly pb::MessageParser<ServiceRobotResp> _parser = new pb::MessageParser<ServiceRobotResp>(() => new ServiceRobotResp());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServiceRobotResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::webwx.RespRobotReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServiceRobotResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServiceRobotResp(ServiceRobotResp other) : this() {
      cmd_ = other.cmd_;
      ChatMsg = other.chatMsg_ != null ? other.ChatMsg.Clone() : null;
      Operation = other.operation_ != null ? other.Operation.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServiceRobotResp Clone() {
      return new ServiceRobotResp(this);
    }

    /// <summary>Field number for the "cmd" field.</summary>
    public const int CmdFieldNumber = 1;
    private int cmd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Cmd {
      get { return cmd_; }
      set {
        cmd_ = value;
      }
    }

    /// <summary>Field number for the "chatMsg" field.</summary>
    public const int ChatMsgFieldNumber = 2;
    private global::webwx.ChatMsg chatMsg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::webwx.ChatMsg ChatMsg {
      get { return chatMsg_; }
      set {
        chatMsg_ = value;
      }
    }

    /// <summary>Field number for the "operation" field.</summary>
    public const int OperationFieldNumber = 3;
    private global::webwx.Operation operation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::webwx.Operation Operation {
      get { return operation_; }
      set {
        operation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServiceRobotResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServiceRobotResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Cmd != other.Cmd) return false;
      if (!object.Equals(ChatMsg, other.ChatMsg)) return false;
      if (!object.Equals(Operation, other.Operation)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Cmd != 0) hash ^= Cmd.GetHashCode();
      if (chatMsg_ != null) hash ^= ChatMsg.GetHashCode();
      if (operation_ != null) hash ^= Operation.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Cmd != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Cmd);
      }
      if (chatMsg_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ChatMsg);
      }
      if (operation_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Operation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Cmd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cmd);
      }
      if (chatMsg_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChatMsg);
      }
      if (operation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Operation);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServiceRobotResp other) {
      if (other == null) {
        return;
      }
      if (other.Cmd != 0) {
        Cmd = other.Cmd;
      }
      if (other.chatMsg_ != null) {
        if (chatMsg_ == null) {
          chatMsg_ = new global::webwx.ChatMsg();
        }
        ChatMsg.MergeFrom(other.ChatMsg);
      }
      if (other.operation_ != null) {
        if (operation_ == null) {
          operation_ = new global::webwx.Operation();
        }
        Operation.MergeFrom(other.Operation);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Cmd = input.ReadInt32();
            break;
          }
          case 18: {
            if (chatMsg_ == null) {
              chatMsg_ = new global::webwx.ChatMsg();
            }
            input.ReadMessage(chatMsg_);
            break;
          }
          case 26: {
            if (operation_ == null) {
              operation_ = new global::webwx.Operation();
            }
            input.ReadMessage(operation_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
